### ISSUE TITLE
[BUG] Generated Link is without https

### ISSUE THREAD

**Issue by mariushosting** [RoastSlav/quickdrop#1]
The automatic generated link is without https

![link](https://github.com/user-attachments/assets/c301e477-2da9-4f16-aac9-1ffab6626d2d)

this should be with https

**Comment by RoastSlav** [comment]
I assume you have it behind a reverse proxy?

**Comment by mariushosting** [comment]
> I assume you have it behind a reverse proxy?

Yes sure.

**Comment by RoastSlav** [comment]
I have updated the app to respect "X-Forwarded-Proto" header if it's behind a reverse proxy that is set up to forward it. In app support for HTTPS certs will take more time.

**Comment by mariushosting** [comment]
> I have updated the app to respect "X-Forwarded-Proto" header if it's behind a reverse proxy that is set up to forward it. In app support for HTTPS certs will take more time.

Thank you.
