### ISSUE TITLE
Sharing links without password protection.

### ISSUE THREAD

**Issue by nicktheone** [RoastSlav/quickdrop#12]
Right now I have my Quickdrop instance exposed to the internet through a Cloudflare tunnel. Given that the service is built for quick and easy file sharing between friends and colleagues I thought it sounded ok for me to expose it. Of course I put it behind password protection, using the provided setting.

My problem is if I want to share a file with someone I need to also share the access password. That poses a problem because I either share the same password, allowing anyone I've ever shared a link with to also access the upload interface (something I may not want them to) or I need to regularly cycle the access password, completely locking out whoever I've already shared a file with that may still want to download said file.

From an ease of use perspective I think it'd be great if we had the choice of allowing direct downloads from shared links without the need for accessing the upload UI/using the password. Is it something that can be implemented?

**Comment by RoastSlav** [comment]
Hello, right now if a file is also password protected another additional button shows up "Share" that generates a link that bypasses all passwords including the app password for one download. I'm working right now to have the button appear if the app password is enabled too.

**Comment by RoastSlav** [comment]
I will probably have the allowed number of downloads per link be adjustable.

**Comment by nicktheone** [comment]
Thank you.

Il giorno sab 14 dic 2024 alle ore 12:29 Rostislav ***@***.***>
ha scritto:
