### ISSUE TITLE
Remove View Files link

### ISSUE THREAD

**Issue by WildMudd** [RoastSlav/quickdrop#5]
Hi there,

Wonderful project, Can I ask how to remove View Files from the front page, I just want to share the link of the file, and I don't want anyone browsing for uploaded files.

Thanks

**Comment by RoastSlav** [comment]
I will not be removing this feature, as I believe it is necessary. However, in the next update, I will be adding a checkbox option when uploading a file. This checkbox will allow users to hide the file from the "View Files" page if desired.
